safe: true
markdown: kramdown
exclude: [node_modules, bower_components, vendor]
url: https://hide212131.github.io/jhipster.github.io
github_repository_url: https://hide212131.github.io/jhipster.github.io
kramdown:
  input: GFM
plugins_dir:
  - jekyll-redirect-from
  - jemoji
whitelist:
  - jekyll-redirect-from
  - jemoji
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
baseurl: /jhipster.github.io
